# Generated by Django 5.0.3 on 2024-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_picturelink_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PictureLink',
        ),
    ]
