# Generated by Django 5.0.3 on 2024-03-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_video_delete_picturelink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Blog',
        ),
    ]
