# Generated by Django 5.0.3 on 2024-03-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teammember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Team',
        ),
    ]
